### ISSUE TITLE
Issue 6 (For milestone 3): Training the model 

### ISSUE THREAD

**Issue by Sconee** [Sconee/Customer-churn-rate-analysis#7]
- [ ] Data Splitting
- [ ] Bootstrapping
- [ ] Cross Validation (Basic, repeated or LOOCV)
- [ ] Model training for either classification, regression or clustering
- [ ] Model performance comparison using resamples
